#ifndef DISCOVERY_HELPER_OPERATOR_H
#define DISCOVERY_HELPER_OPERATOR_H

#include <string>
#include <coros_messages/HelloMsg.h> //This contains message structure of Hello protocol. auto-generated by ROS
#include "coros_operator/SimpleOperator.h" //this is the parent class of Discovery Robot Client class.

#include "coros_kb/AgentState.h"




class DiscoveryHelperOperator : public SimpleOperator
{
  
public:
  
  //constructor that initialized the robotID and the node name
	DiscoveryHelperOperator(const std::string& nodeName);

  //helloCallback function is executed whenever a new hello message is received
  void helloCallback(const coros_messages::HelloMsg::ConstPtr& msg);

protected:
  
  //init callbacks
  void init(); 

  std::string process(BaseMessage*){ return "";}

private:

  std::vector<AgentState*> myNeighbors;

};

#endif // DISCOVERY_HELPER_OPERATOR_H
